import Head from 'next/head'
import AboutMe from '../components/AboutMe'
import Contact from '../components/Contact'
import Form from '../components/Form'
import Header from '../components/Header'
import Hero from '../components/Hero'

export default function Home() {
    return (
        <div>
            <Head>
                <title>HexalCorp</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <Hero />
            <AboutMe />
            <Contact
                title="Get In Touch"
                secTitle="In order to get in touch use the contact form below:"
            >
                <Form />
            </Contact>
        </div>
    )
}
